//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriUrun
    {
        public int favoriUrunId { get; set; }
        public Nullable<int> favoriId { get; set; }
        public Nullable<int> urunId { get; set; }
    
        public virtual Favoriler Favoriler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
