//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoBilgisi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KargoBilgisi()
        {
            this.Satis = new HashSet<Sati>();
            this.Satislars = new HashSet<Satislar>();
            this.SatislarTablosus = new HashSet<SatislarTablosu>();
        }
    
        public int kargoBilgisiId { get; set; }
        public Nullable<int> kargoId { get; set; }
        public string il { get; set; }
        public string ilce { get; set; }
        public string acikAdres { get; set; }
        public string kargoDurumu { get; set; }
    
        public virtual Kargolar Kargolar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sati> Satis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Satislar> Satislars { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SatislarTablosu> SatislarTablosus { get; set; }
    }
}
