//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KargoBilgileri
    {
        public int kargoId { get; set; }
        public Nullable<int> teslimatAdresi { get; set; }
        public string kargoAdi { get; set; }
        public string kargoTakipNo { get; set; }
        public string kargoDurumu { get; set; }
    
        public virtual Adresler Adresler { get; set; }
    }
}
