//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SepetUrun
    {
        public int sepetUrunId { get; set; }
        public Nullable<int> sepetId { get; set; }
        public Nullable<int> urunId { get; set; }
        public int urunSayisi { get; set; }
    
        public virtual Sepetler Sepetler { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
