//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ShopCartEntities : DbContext
    {
        public ShopCartEntities()
            : base("name=ShopCartEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Adresler> Adreslers { get; set; }
        public virtual DbSet<Bolgeler> Bolgelers { get; set; }
        public virtual DbSet<Favoriler> Favorilers { get; set; }
        public virtual DbSet<FavoriUrun> FavoriUruns { get; set; }
        public virtual DbSet<KargoBilgileri> KargoBilgileris { get; set; }
        public virtual DbSet<KargoBilgisi> KargoBilgisis { get; set; }
        public virtual DbSet<Kargolar> Kargolars { get; set; }
        public virtual DbSet<Kategoriler> Kategorilers { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilars { get; set; }
        public virtual DbSet<Markalar> Markalars { get; set; }
        public virtual DbSet<OdemeYontemleri> OdemeYontemleris { get; set; }
        public virtual DbSet<Sati> Satis { get; set; }
        public virtual DbSet<Sepetler> Sepetlers { get; set; }
        public virtual DbSet<SepetUrun> SepetUruns { get; set; }
        public virtual DbSet<Test> Tests { get; set; }
        public virtual DbSet<Urunler> Urunlers { get; set; }
        public virtual DbSet<UrunOzellikleri> UrunOzellikleris { get; set; }
        public virtual DbSet<Yorumlar> Yorumlars { get; set; }
        public virtual DbSet<URUNKATEGORIMARKA> URUNKATEGORIMARKAs { get; set; }
        public virtual DbSet<Satislar> Satislars { get; set; }
        public virtual DbSet<SatislarTablosu> SatislarTablosus { get; set; }
    
        public virtual ObjectResult<SP_GETFAVORIDETAYWITHID_Result> SP_GETFAVORIDETAYWITHID(Nullable<int> musteriId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETFAVORIDETAYWITHID_Result>("SP_GETFAVORIDETAYWITHID", musteriIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSepetDetay_Result> SP_GetSepetDetay(Nullable<int> musteriId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSepetDetay_Result>("SP_GetSepetDetay", musteriIdParameter);
        }
    
        public virtual ObjectResult<SP_GETSEPETDETAYWITHID_Result> SP_GETSEPETDETAYWITHID(Nullable<int> musteriId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GETSEPETDETAYWITHID_Result>("SP_GETSEPETDETAYWITHID", musteriIdParameter);
        }
    
        public virtual ObjectResult<SP_SEPETDETAY_Result> SP_SEPETDETAY(Nullable<int> musteriId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEPETDETAY_Result>("SP_SEPETDETAY", musteriIdParameter);
        }
    
        public virtual ObjectResult<SP_SEPETDETAY1_Result> SP_SEPETDETAY1(Nullable<int> musteriId)
        {
            var musteriIdParameter = musteriId.HasValue ?
                new ObjectParameter("MusteriId", musteriId) :
                new ObjectParameter("MusteriId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_SEPETDETAY1_Result>("SP_SEPETDETAY1", musteriIdParameter);
        }
    
        public virtual ObjectResult<GetUrunDetayWithId_Result> GetUrunDetayWithId(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUrunDetayWithId_Result>("GetUrunDetayWithId", urunIdParameter);
        }
    
        public virtual ObjectResult<GetUrunDetayWithUrunId_Result> GetUrunDetayWithUrunId(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUrunDetayWithUrunId_Result>("GetUrunDetayWithUrunId", urunIdParameter);
        }
    
        public virtual ObjectResult<SP_GetUrunDetayWithUrunId_Result> SP_GetUrunDetayWithUrunId(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetUrunDetayWithUrunId_Result>("SP_GetUrunDetayWithUrunId", urunIdParameter);
        }
    
        public virtual ObjectResult<SP_YeniUrunDetayWithUrunId_Result> SP_YeniUrunDetayWithUrunId(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_YeniUrunDetayWithUrunId_Result>("SP_YeniUrunDetayWithUrunId", urunIdParameter);
        }
    
        public virtual ObjectResult<SP_GetSalesInfo_Result> SP_GetSalesInfo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_GetSalesInfo_Result>("SP_GetSalesInfo");
        }
    
        public virtual ObjectResult<GetUrunGuncelleDetayWithId_Result> GetUrunGuncelleDetayWithId(Nullable<int> urunId)
        {
            var urunIdParameter = urunId.HasValue ?
                new ObjectParameter("urunId", urunId) :
                new ObjectParameter("urunId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetUrunGuncelleDetayWithId_Result>("GetUrunGuncelleDetayWithId", urunIdParameter);
        }
    }
}
