//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class URUNKATEGORIMARKA
    {
        public int UrunId { get; set; }
        public string UrunAdi { get; set; }
        public int urunFiyati { get; set; }
        public string urunResmi { get; set; }
        public int urunStokMiktari { get; set; }
        public string kategoriAdi { get; set; }
        public string markaAdi { get; set; }
    }
}
