//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopCart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorumlar
    {
        public int yorumId { get; set; }
        public Nullable<int> kullaniciId { get; set; }
        public Nullable<int> urunId { get; set; }
        public string yorumMetni { get; set; }
        public Nullable<System.DateTime> yorumTarihi { get; set; }
    
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Urunler Urunler { get; set; }
    }
}
